name: Run ES Tests

on:
  push:
    branches:
      - s3-trigger
jobs:
  plugin-avilability:
    name: Check Plugin Availability
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: opendistro-for-elasticsearch/index-management
      - run: git checkout tags/v1.3.0.1

          
