name: Run ES Tests

on:
  push:
    branches:
      - s3-trigger
jobs:
  plugin-avilability:
    name: Check Plugin Availability
    runs-on: ubuntu-latest
    steps:
      - name: RUN ES Docker
        run: |
          echo "Running Docker"
          docker pull opendistroforelasticsearch/opendistroforelasticsearch:1.3.0
          docker run -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opendistroforelasticsearch/opendistroforelasticsearch:1.3.0
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: opendistro-for-elasticsearch/index-management
          ref: odfe-1.3.0.1
      - name: RUN ES Tests
        run: |
          sleep 45
          curl -XGET https://localhost:9200 -u admin:admin --insecure
          #./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200

          
