name: What the F is this

on:
  push:
    branches:
      - s3-trigger
jobs:
  Test-ISM-Plugin:
    name: Checkout Elastic Repo
    runs-on: [ubuntu-16.04]
    steps:
      - name: Checkout Elastic Git Repo
        run: |
          git clone https://github.com/elastic/elasticsearch.git
          
          ls -ltr
          tar cvzf elasticsearch.tar.gz elasticsearch
          ls -ltr
          
          
      
