name: What the F is this

on:
  push:
    branches:
      - s3-trigger
jobs:
  Test-ISM-Plugin:
    name: Test ES Docker Container
    runs-on: [ubuntu-16.04]
    strategy:
      matrix:
        java: [12]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: opendistro-for-elasticsearch/index-management
          ref: master
      - name: Set Up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run Docker Container
        run: |
          sleep 10
          ls -ltr
          cd ..
          #echo "FROM opendistroforelasticsearch/opendistroforelasticsearch:1.3.0" >> Dockerfile
          #echo "RUN /usr/share/elasticsearch/bin/elasticsearch-plugin remove opendistro_security" >> Dockerfile
          
          #docker build -t odfe-http:no-security .
          #docker run -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" odfe-http:no-security
          
          #sleep 45
          cd index-management
          #./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200
          
          
      
