name: Process Debian Artifacts

on:
  push:
    branches:
      - s3-trigger
jobs:
  plugin-avilability:
    name: Check Plugin Availability
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [12]
    steps:
      - name: Set up AWS Cred
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/checkout@v1
      - name: Checkout ISM
        uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/index-management
          ref: opendistro-1.3
      - name: Run Something
        run: |
          echo `pwd`
          java -version
          cd ..
          cd opendistro-build/elasticsearch/linux_distributions
          odfe_version=`../bin/version-info --od`
          echo $odfe_version
          cd ../../..
          aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/tarball/opendistro-elasticsearch/opendistroforelasticsearch-1.3.0.tar.gz .
          tar -zxf opendistroforelasticsearch-1.3.0.tar.gz
          cd opendistroforelasticsearch-1.3.0
          sed -i /install_demo_configuration/d opendistro-tar-install.sh
          /bin/elasticsearch-plugin remove opendistro_security
          
          nohup ./opendistro-tar-install.sh &
          sleep 45
          curl http://localhost:9200
          
          
      
