name: Process Debian Artifacts

on:
  push:
    branches:
      - s3-trigger
jobs:
  plugin-avilability:
    name: Check Plugin Availability
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: opendistro-for-elasticsearch/alerting
          ref: opendistro-1.4
      - name: List Repo
        run: |
          echo `pwd`
          echo "This is a test message" > /home/runner/work/opendistro-build/test_message.txt
          
          cat /home/runner/work/opendistro-build/test_message.txt
        
      
