name: Process Debian Artifacts

on:
  push:
    branches:
      - s3-trigger
jobs:
  plugin-avilability:
    name: Check Plugin Availability
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: opendistro-for-elasticsearch/alerting
          ref: opendistro-1.4
      - name: List Repo
        run: |
          echo `pwd`
          echo "This is a test message" > /home/runner/work/opendistro-build/test_message.txt
          
          cat /home/runner/work/opendistro-build/test_message.txt
      - name: Send mail
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          # Read file contents as body:
          body: /home/runner/work/opendistro-build/test_message.txt
          to: sngri@amazon.com
          from: Rishabh Singh
          # Optional content type:
          content_type: text/html
        
      
