name: What the F is this

on:
  push:
    branches:
      - s3-trigger
jobs:
  Test-ISM-Plugin:
    name: Test ES Docker Container
    runs-on: [ubuntu-16.04]
    strategy:
      matrix:
        java: [12]
    steps:
      - uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/index-management
          ref: master
      - name: Set Up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run Docker Container
        run: |
          ls -ltr
          echo "Next"
          cd ..
          echo "skdhskalhdksla"
          ls -ltr

          
          
      
