name: Process Debian Artifacts

on:
  push:
    branches:
      - s3-trigger
jobs:
  plugin-avilability:
    name: Check Plugin Availability
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        run: |
          ls -ltr
        
      
