name: Process Debian Artifacts

on:
  push:
    branches:
      - s3-trigger
jobs:
  plugin-avilability:
    name: Check Plugin Availability
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Checking Availability
        run: |
          #!/bin/bash
          CURRENT_NO_PLUGINS=6
          plugin_arr=()
          unavailable_plugin=()
          PLUGINS="opendistro-sql/opendistro_sql opendistro-alerting/opendistro_alerting opendistro-job-scheduler/opendistro-job-scheduler opendistro-security/opendistro_security performance-analyzer/opendistro_performance_analyzer opendistro-index-management/opendistro_index_management"
          
          cd elasticsearch/bin
          ls -ltr
          OD_VERSION=`./version-info --od`
          echo "$OD_VERSION"
          cd /home/runner/work/opendistro-build
          mkdir plugins
          ls -ltr
          cd plugins
          
          for item in $PLUGINS
          do
            plugin_folder=`echo $item|awk -F/ '{print $1}'`
            plguin_item=`echo $item|awk -F/ '{print $2}'`
            plugin_arr+=( $plguin_item )
            aws s3 cp s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/elasticsearch-plugins/$plugin_folder/ . --recursive --exclude "*" --include "$plguin_item-$OD_VERSION*"
          done
          ls -ltr
          tot_plugins=`ls|wc -l`
          echo $tot_plugins
          echo "${#plugin_arr[*]}"
          
          if [ $tot_plugins == $CURRENT_NO_PLUGINS ]
          then
              echo "All plugins available"
          else
              curr_plugins=`ls`
              echo $curr_plugins
              for plgin in ${plugin_arr[*]}
              do
                if echo $curr_plugins|grep -q $plgin
                then
                    echo "$plgin exists"
                else
                    unavailable_plugin+=( $plgin )
                fi
              done
          fi
          
          cd /home/runner/work/opendistro-build/opendistro-build/
          if [ ${#unavailable_plugin[*]} > 0 ]
          then
              echo "<h2>Below plugins are not yet available for ODFE-$OD_VERSION</h2>" >> message.md
              echo "<ol>" >> message.md
              for item in ${unavailable_plugin[*]}
              do
                echo "<li>$item</li>" >> message.md
              done
              echo "</ol>" >> message.md
          else
              echo <h2> All plugins are available </h2> >> message.md
          fi
      - name: Send mail
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Opendistro for Elasticsearch Build - Daily Run (Plugin Status)
          # Read file contents as body:
          body: file://message.md
          to: sngri@amazon.com
          from: Opendistro Elasticsearch
          # Optional content type:
          content_type: text/html
          
        
      
